"""Add current workout day

Revision ID: 32836f18274f
Revises: d18353efa270
Create Date: 2024-11-13 17:03:30.948735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32836f18274f'
down_revision: Union[str, None] = 'd18353efa270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('current_workout_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_details', 'current_workout_day')
    # ### end Alembic commands ###
