"""Add series and repetitions to day exercises

Revision ID: 57824709348d
Revises: 9d1c7184adb1
Create Date: 2024-11-17 17:21:34.157074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57824709348d'
down_revision: Union[str, None] = '9d1c7184adb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_exercises', sa.Column('series', sa.String(), nullable=True))
    op.add_column('day_exercises', sa.Column('repetitions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_exercises', 'repetitions')
    op.drop_column('day_exercises', 'series')
    # ### end Alembic commands ###
