"""Add foreign key workout to user details

Revision ID: 6592a2139944
Revises: 43a31bf6854d
Create Date: 2024-11-13 15:40:00.334044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6592a2139944'
down_revision: Union[str, None] = '43a31bf6854d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_details', 'workouts', ['workout_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_details', type_='foreignkey')
    # ### end Alembic commands ###
